/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/*
 * Copyright Vladimir Dzyuba
 * From Implementation of the Flexics pattern sampler.
 * Dzyuba, V., van Leeuwen, M., & De Raedt, L. (2016). Flexible constrained sampling with guarantees for pattern mining. arXiv:1610.09263.
*/

package malb.m4ri;

public class SWIGTYPE_p_mzd_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_mzd_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_mzd_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_mzd_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

